export const ACTIONS_MEDIAS =
    {
        SET_ACTIVE_MEDIA: "SET_ACTIVE_MEDIA",
        SET_PLAYED_MEDIA: "SET_PLAYED_MEDIA",
        SET_PLAY_STATE: "SET_PLAY_STATE",
        SET_MEDIAS_LIST: "SET_MEDIAS_LIST"
    };