export const ACTIONS_MEDIAS =
    {
        SET_ACTIVE_EPISODE: "SET_ACTIVE_EPISODE",
        SET_PLAYED_EPISODE: "SET_PLAYED_EPISODE",
        SET_PLAY_STATE: "SET_PLAY_STATE",
        SET_MEDIAS_LIST: "SET_MEDIAS_LIST",
        SET_CURRENT_MEDIA: "SET_CURRENT_MEDIA"
    };