export const ACTIONS_SETTINGS =
    {
        SET_FILTERED_VALUES: "SET_SETTINGS_FILTERED_VALUES",
        IS_MOBILE_DRAWER_OPEN: "IS_MOBILE_DRAWER_OPEN",
        SET_COOKIE_CONSENT: "SET_COOKIE_CONSENT"
    };